<?php
$quote = $block->getQuote();
$url = $block->getCheckoutUrl();
$dataLang = $block->getLanguage();
$dataVariant = $quote->getData('collector_btype');
$publicToken = $quote->getData('collector_public_token');
?>

<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
    });
</script>
<div id="collector-checkout" class="collector-checkout">
    <script src="<?php echo $url; ?>" data-token="<?php echo $publicToken; ?>"
            data-lang='<?php echo $dataLang; ?>' <?php echo $dataVariant; ?>></script>
</div>
<?php
$this->clearSession();
?>