<?php
/*$collectorSession = $block->getCollectorSession();
$url = $collectorSession->getCollectorUrl('');
$dataLang = $collectorSession->getCollectorLanguage('');
$dataVariant = $collectorSession->getCollectorDataVariant('');
$publicToken = $collectorSession->getCollectorPublicToken('');
$collectorSession->setCollectorPublicToken('');*/
        file_put_contents("var/log/coldev.log", "Success.phtml test 1\n", FILE_APPEND);
$quote = $block->getQuote();
        file_put_contents("var/log/coldev.log", "Success.phtml test 2\n", FILE_APPEND);
        file_put_contents("var/log/coldev.log", "Success.phtml test 3\n", FILE_APPEND);
$url = $block->getCheckoutUrl();
        file_put_contents("var/log/coldev.log", "Success.phtml test 4\n", FILE_APPEND);
$dataLang = $block->getLanguage();
        file_put_contents("var/log/coldev.log", "Success.phtml test 5\n", FILE_APPEND);
$dataVariant = $quote->getData('collector_btype');
        file_put_contents("var/log/coldev.log", "Success.phtml test 6\n", FILE_APPEND);
$publicToken = $quote->getData('collector_public_token');
        file_put_contents("var/log/coldev.log", "Success.phtml test 7   \n", FILE_APPEND);
?>

<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
    });
</script>
<div id="collector-checkout" class="collector-checkout">
    <script src="<?php echo $url; ?>" data-token="<?php echo $publicToken; ?>"
            data-lang='<?php echo $dataLang; ?>' <?php echo $dataVariant; ?>></script>
</div>
<?php
$this->clearSession();
?>